export const categories = [
  ['cafe', 'internet_cafe', 'coffee', 'bakery'],
  [
    'restaurant',
    'fast_food',
    'food',
    'food_court',
    'ice_cream',
    'food_truck',
    'taco_shop',
    'pizza_restaurant',
    'burger_restaurant',
  ],
  ['museum', 'art_gallery', 'aquarium', 'library'],
  ['bar', 'nightclub', 'pub', 'brewery'],
  [
    'stadium',
    'amusement_park',
    'bowling_alley',
    'casino',
    'movie_theater',
    'stadium',
    'zoo',
    'ice_rink',
  ],
  [
    'shopping_mall',
    'book_store',
    'clothing_store',
    'florist',
    'jewelry_store',
    'pet_store',
    'shoe_store',
    'shopping_mall',
    'store',
  ],
  [
    'tourist_attraction',
    'place_of_worship',
    'city_hall',
    'courthouse',
    'embassy',
    'fire_station',
    'local_government_office',
    'police',
    'post_office',
    'subway_station',
  ],
  ['nightlife', 'bar', 'nightclub', 'pub', 'winery'],
];

export const singleCategories = [
  'cafe',
  'bakery',
  'restaurant',
  'museum',
  'tourist_attraction',
  'park',
  'shopping_mall',
  'nature_reserve',
  'public_transportation_station',
  'nightlife',
];
